settings:
  title: 'Status Page 9'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
 # - id: workers-cloudflare-com # unique identifier
 #   name: workers.cloudflare.com
 #   description: 'You write code. They handle the rest.' # default=empty
 #   url: 'https://workers.cloudflare.com/' # URL to fetch
 #   method: GET # default=GET
 #   expectStatus: 200 # operational status, default=200
 #   followRedirect: false # should fetch follow redirects, default=false
 #   linkable: false # allows the title to be a link, default=true

  - id: tou-cloudpeek-xyz
    name: The Cloudpeek App1
    url: 'https://tou.cloudpeek.xyz/mons1234'
    method: GET
    expectStatus: 200

  - id: apac-ankur-demo
    name: The BP Demo
    url: 'https://apac-ankbp.byteplus-demo.com/mons1234'
    method: GET
    expectStatus: 200

  - id: www-playpark-com
    name: The PP WWWW
    url: 'https://www.playpark.com/'
    method: GET
    expectStatus: 302

 - id: street-playpark-com
    name: The PP streetball
    url: 'https://streetballers.playpark.com/'
    method: GET
    expectStatus: 302

 - id: app-odd-me
    name: The Oddle App
    url: 'https://app.oddle.me/'
    method: GET
    expectStatus: 200
